//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PODBProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetOwnerProfile
    {
        public int profileId { get; set; }
        public string Id { get; set; }
        public string fullName { get; set; }
        public string gender { get; set; }
        public string street { get; set; }
        public string subdivision { get; set; }
        public string barangay { get; set; }
        public string contactNumber { get; set; }
        public string email { get; set; }
        public System.DateTime registerDate { get; set; }
        public System.DateTime updateDate { get; set; }
        public int imageID { get; set; }
    }
}
