//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PODBProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Announcement
    {
        public int announceId { get; set; }
        [DisplayName("Announcement Title")]
        public string announceTitle { get; set; }
        [DisplayName("Announcement Text")]
        public string announceText { get; set; }
        public int imageID { get; set; }
        public System.DateTime announceDate { get; set; }
        public string Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Image Image { get; set; }
    }
}
