//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PODBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVOEmployee
    {
        public string accountId { get; set; }
        public string employeeId { get; set; }
        public string employeeName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
