//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PODBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PetProfile()
        {
            this.Adoptions = new HashSet<Adoption>();
            this.Services = new HashSet<Service>();
        }
    
        public int petId { get; set; }
        public string Id { get; set; }
        public string petName { get; set; }
        public string petType { get; set; }
        public string petBreed { get; set; }
        public string gender { get; set; }
        public string mChipStatus { get; set; }
        public string mChipId { get; set; }
        public string nueterStatus { get; set; }
        public int imageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoption> Adoptions { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Image Image { get; set; }
        public virtual PetProfile PetProfile1 { get; set; }
        public virtual PetProfile PetProfile2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
    }
}
