//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PODBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int reportId { get; set; }
        public string Id { get; set; }
        public string reportType { get; set; }
        public string reportTitle { get; set; }
        public string reportText { get; set; }
        public System.DateTime reportDate { get; set; }
        public string photoId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
