//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PODBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int serviceId { get; set; }
        public string serviceType { get; set; }
        public string Id { get; set; }
        public int petId { get; set; }
        public System.DateTime serivceDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PetProfile PetProfile { get; set; }
    }
}
