//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PODBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violation
    {
        public int violationId { get; set; }
        public string violationType { get; set; }
        public string violationTitle { get; set; }
        public string violatorName { get; set; }
        public string violationText { get; set; }
        public string violationPenalty { get; set; }
        public System.DateTime violationDate { get; set; }
        public string Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
